Error handling improvements for AWS test

diff --git a/scripts/integration b/scripts/integration
--- a/scripts/integration
+++ b/scripts/integration
@@ -1,8 +1,9 @@
 #!/usr/bin/env bash
 
 SCRIPTDIR=$( cd ${0%/*} && pwd)
-TESTS="a_smoke environment exec_context seed template cold_storage"
+TESTS="a_smoke environment exec_context seed template"
 VAULT_TESTS="aws"
+GPG_TESTS="cold_storage"
 export VAULT_AWS_PATH="travis/aws/creds/aomi"
 export VAULT_SECRET_PATH="secrets/aomi"
 
@@ -17,10 +18,20 @@ if [ $# == 1 ] ; then
     fi
 fi
 
-SCRIPT_DIR=$(cd ${0%/*} && pwd)
-CIDIR=${SCRIPT_DIR%/*}
+CIDIR=${SCRIPTDIR%/*}
 BATSGIT="${CIDIR}/.bats-git"
 BATSBIN="${CIDIR}/.bats"
+
+if ! which shyaml &> /dev/null ; then
+    echo "shyaml required"
+    exit 1
+fi
+
+if [ -z "$TRAVIS" ] && ! which gpg2 &> /dev/null ; then
+    echo "gpg2 required"
+    exit 1
+fi
+
 if [ -z "$TRAVIS" ] ; then
     . "${CIDIR}/.ci-env/bin/activate"
 fi
@@ -36,6 +47,18 @@ if [ ! -d "$BATSBIN" ] ; then
     ./install.sh "$BATSBIN"
 fi
 
+# when switching between local osx/docker you can end up
+# with incorrect vault binaries
+if [ -d "${CIDIR}/.vault" ] ; then
+    if [ "$(uname -s)" == "Darwin" ] && \
+           ! file "${CIDIR}/.vault/vault" | grep "Mach-O" &> /dev/null ; then
+        rm -rf "${CIDIR}/.vault"
+    elif [ "$(uname -s)" == "Linux" ] && \
+             ! file "${CIDIR}/.vault/vault" | grep LSB &> /dev/null ; then
+        rm -rf "${CIDIR}/.vault"
+    fi
+fi
+
 if [ ! -d "${CIDIR}/.vault" ] ; then
     mkdir -p "${CIDIR}/.vault/"
     OS=$(uname -s)
@@ -48,9 +71,9 @@ if [ ! -d "${CIDIR}/.vault" ] ; then
     wget -O  "/tmp/vault.zip"  "$URL"
     unzip -d "${CIDIR}/.vault" "/tmp/vault.zip"
     chmod +x "${CIDIR}/.vault/vault"
-    PATH="${PATH}:${CIDIR}/.vault"
-    export PATH
 fi
+PATH="${PATH}:${CIDIR}/.vault"
+export PATH
 
 if [ ! -z "$TRAVIS" ] && [ ! -z "$CI" ] ; then
     echo "Looking under couch for Vault token"
@@ -63,18 +86,21 @@ EXEC_TESTS=""
 for a_test in $TESTS ; do
     EXEC_TESTS="${EXEC_TESTS} ${CIDIR}/tests/integration/${a_test}.bats"
 done
+if [ -z "$TRAVIS" ] ; then
+    EXEC_TESTS="${EXEC_TESTS} ${CIDIR}/tests/integration/${GPG_TESTS}.bats"
+fi
+
 CI_TOKEN="${CIDIR}/.aomi-test/vault-token"
 if [ -e "$CI_TOKEN" ] ; then
     VAULT_TOKEN=$(cat "$CI_TOKEN")
-fi
-if [ -e "${HOME}/.vault-token" ] ; then
+elif [ -e "${HOME}/.vault-token" ] ; then
     VAULT_TOKEN=$(cat "${HOME}/.vault-token")
 fi
 
 if [ ! -z "$VAULT_TOKEN" ] && \
        [ ! -z "$VAULT_ADDR" ] ; then
     echo "Vault detected..."
-    if VAULT_TOKEN=$VAULT_TOKEN vault read -field=refresh_interval "$VAULT_SECRET_PATH" &> /dev/null ; then
+    if VAULT_TOKEN=$VAULT_TOKEN "${CIDIR}/.vault/vault" read -field=refresh_interval "$VAULT_SECRET_PATH" &> /dev/null ; then
         echo "Vault server seems legit..."
         if [ ! -d "${CIDIR}/.aomi-test" ] ; then
             mkdir -p "${CIDIR}/.aomi-test"
@@ -84,7 +110,11 @@ if [ ! -z "$VAULT_TOKEN" ] && \
             EXEC_TESTS="${EXEC_TESTS} ${CIDIR}/tests/integration/${a_test}.bats"
         done
         echo "$VAULT_ADDR" > "${CIDIR}/.aomi-test/vault-addr"
+    else
+        rm -rf "${CIDIR}/.aomi-test"
     fi
+else
+    rm -rf "${CIDIR}/.aomi-test"
 fi
 
 if [ ! -e "${CIDIR}/.aomi-test/vault-token" ] ; then
@@ -106,6 +136,6 @@ if [ ! -z "$TRAVIS" ] && \
        [ ! -z "$CI" ] && \
        [ -e "${CIDIR}/.aomi-test/vault-token" ] ; then
     echo "Tearing up our Vault token"
-    VAULT_TOKEN=$VAULT_TOKEN vault write -f auth/token/revoke-self &> /dev/null
+    VAULT_TOKEN=$VAULT_TOKEN "${CIDIR}/.vault/vault" write -f auth/token/revoke-self &> /dev/null
 fi
 exit "$RC"
